### ISSUE TITLE
Failed to import "YetAnotherPicSearch“

### ISSUE THREAD

**Issue by sjxkfnskdd** [lgc-NB2Dev/YetAnotherPicSearch#138]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch:2.0.1
llonebot3.30.0
nonebot2.3.3

### 列出安装的 Python 包

3.11

### 如何复现

参考#125，降级 Pydantic至v1版本依然是同样的报错

### 实际行为

PS D:\Bot\bot04\bot04> nb run
使用 Python: D:\Bot\bot04\bot04\.venv\Scripts\python.exe
08-24 12:01:50 [SUCCESS] nonebot | NoneBot is initializing...
08-24 12:01:50 [INFO] nonebot | Current Env: prod
08-24 12:01:50 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
08-24 12:01:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
08-24 12:01:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_withdraw"
08-24 12:01:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
08-24 12:01:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
08-24 12:01:51 [ERROR] nonebot | Failed to import "YetAnotherPicSearch"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\97502\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\__init__.py", line 7, in <module>
    from . import __main__ as __main__
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\__main__.py", line 36, in <module>
    from .cache import msg_cache
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\cache.py", line 10, in <module>
    from .config import config
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\config.py", line 58, in <module>
    config = get_plugin_config(ConfigModel)
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\compat.py", line 225, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\pydantic\type_adapter.py", line 373, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ConfigModel
saucenao_api_key
  Field required [type=missing, input_value={'driver': '~fastapi', 'h....timedelta(seconds=120)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
08-24 12:01:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session"
08-24 12:01:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_access_control_api"
08-24 12:01:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
08-24 12:01:52 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
08-24 12:01:52 [INFO] nonebot_plugin_access_control | use inmemory rate_limit_token storage
08-24 12:01:52 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_access_control"
08-24 12:01:52 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_tortoise_orm"
08-24 12:01:52 [SUCCESS] nonebot_plugin_tortoise_orm | 数据库: 添加模型: nonebot_plugin_setu_now.database
08-24 12:01:52 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_setu_now"
08-24 12:01:52 [WARNING] nonebot_plugin_repeater | [复读姬] 未发现配置项 `repeater_group` , 采用默认值: []
08-24 12:01:52 [WARNING] nonebot_plugin_repeater | [复读姬] 未发现配置项 `repeater_min_message_length` , 采用默认值: 1
08-24 12:01:52 [WARNING] nonebot_plugin_repeater | [复读姬] 未发现配置项 `repeater_min_message_times` , 采用默认值: 2
08-24 12:01:52 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_repeater"
08-24 12:01:52 [SUCCESS] nonebot | Running NoneBot...
08-24 12:01:52 [INFO] uvicorn | Started server process [42760]
08-24 12:01:52 [INFO] uvicorn | Waiting for application startup.
08-24 12:01:52 [INFO] nonebot_plugin_apscheduler | Scheduler Started
08-24 12:01:52 [INFO] nonebot_plugin_orm | 没有检测到新的升级操作
08-24 12:01:52 [SUCCESS] nonebot_plugin_tortoise_orm | 数据库: default 连接成功 URL: sqlite:///C:\Users\97502\AppData\Local\nonebot2\nonebot_plugin_tortoise_orm\db.sqlite3
08-24 12:01:52 [INFO] uvicorn | Application startup complete.
08-24 12:01:52 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
08-24 12:01:53 [INFO] uvicorn | ('127.0.0.1', 55002) - "WebSocket /onebot/v11/ws" [accepted]
08-24 12:01:53 [INFO] nonebot | OneBot V11 | Bot 2557731298 connected
08-24 12:01:53 [INFO] websockets | connection open
08-24 12:01:58 [INFO] uvicorn | Shutting down
08-24 12:01:58 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 2557731298 closed by peer
08-24 12:01:58 [INFO] websockets | connection closed
08-24 12:01:59 [INFO] uvicorn | Waiting for application shutdown.
08-24 12:01:59 [INFO] nonebot_plugin_apscheduler | Scheduler Shutdown
08-24 12:01:59 [SUCCESS] nonebot_plugin_tortoise_orm | 数据库: 断开链接
08-24 12:01:59 [INFO] uvicorn | Application shutdown complete.
08-24 12:01:59 [INFO] uvicorn | Finished server process [42760]

**Comment by sjxkfnskdd** [comment]
填过saucenao报错如下
08-24 12:22:11 [ERROR] nonebot | Failed to import "YetAnotherPicSearch"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\97502\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\__init__.py", line 7, in <module>
    from . import __main__ as __main__
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\__main__.py", line 36, in <module>
    from .cache import msg_cache
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\cache.py", line 10, in <module>
    from .config import config
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\config.py", line 8, in <module>
    class ConfigModel(BaseModel):
  File "D:\Bot\bot04\bot04\.venv\Lib\site-packages\YetAnotherPicSearch\config.py", line 13, in ConfigModel
    saucenao_api_key: f9af2733ec9d49d9a3adbd43db7c9fa9f725a129
NameError: name 'f9af2733ec9d49d9a3adbd43db7c9fa9f725a129' is not defined
