### ISSUE TITLE
ascii2d的 色合检索 和 特征检索 结果一样

### ISSUE THREAD

**Issue by rockqtmh** [lgc-NB2Dev/YetAnotherPicSearch#141]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch 2.0.2
PicImageSearch 3.11.2
napcat 4.0.3
nonebot 2.4.0
python 3.13
操作系统 windows server 2022 datacenter

### 如何复现

搜图saucenao匹配度不够就会进行ascii2d检索

### 期望行为

正常使用色合和特征检索

### 实际行为

![56bbd48d-a887-452b-a4df-7b64ddd4d0bd](https://github.com/user-attachments/assets/d233893b-51bc-4512-bc1d-07a4371bccc1)

**Comment by NekoAria** [comment]
是配置了ascii2d 镜像站吗？

**Comment by rockqtmh** [comment]
是的

**Comment by rockqtmh** [comment]
> 是配置了ascii2d 镜像站吗？

请问如何解决呢？

**Comment by NekoAria** [comment]
> 请问如何解决呢？

你试试最新的 `v2.0.3`

**Comment by rockqtmh** [comment]
> > 请问如何解决呢？
> 
> 你试试最新的 `v2.0.3`

更新至2.0.3后启动报错
alconna版本是0.54.0

11-28 11:14:00 [ERROR] nonebot | Failed to import "YetAnotherPicSearch"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 133, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 67, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 205, in load_all_plugins
    return set(
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 257, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\nonebot\bot\.venv\Lib\site-packages\YetAnotherPicSearch\__init__.py", line 8, in <module>
    from . import __main__ as __main__
  File "C:\nonebot\bot\.venv\Lib\site-packages\YetAnotherPicSearch\__main__.py", line 54, in <module>
    async def extract_images(msg: UniMsg[Segment]) -> list[Image]:
  File "C:\Program Files\Python\Python313\Lib\typing.py", line 432, in inner
    return func(*args, **kwds)
  File "C:\Program Files\Python\Python313\Lib\typing.py", line 1473, in __getitem__
    raise TypeError(f"{self} is not a generic class")
TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class

**Comment by NekoAria** [comment]
试试 `v2.0.3.post1`

**Comment by rockqtmh** [comment]
> 试试 `v2.0.3.post1`

还是会报错，我用2.0.2的main.py替换就没问题了

**Comment by NekoAria** [comment]
> 还是会报错，我用2.0.2的main.py替换就没问题了

已更新 `v2.0.3.post2`
