### ISSUE TITLE
更新至2.0.3后启动报错TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class

### ISSUE THREAD

**Issue by Fhm-newbie** [lgc-NB2Dev/YetAnotherPicSearch#142]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch：2.0.3、PicImageSearch：3.11.2、lagrange.onebot、nonebot 2.4.0、python 3.10.12

### 列出安装的 Python 包

aiohttp==3.9.5
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.4.0
APScheduler==3.10.4
arclet-alconna==1.8.34
arclet-alconna-tools==0.7.10
arrow==1.3.0
async-timeout==4.0.3
attrs==23.2.0
Brotli==1.1.0
cache==1.0.3
cachetools==5.3.3
certifi==2024.6.2
charset-normalizer==3.3.2
click==8.1.7
cookit==0.8.1
cssselect==1.2.0
dnspython==2.6.1
email_validator==2.2.0
exceptiongroup==1.2.2
fastapi==0.111.0
fastapi-cli==0.0.4
fleep==1.0.1
frozenlist==1.4.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.2
hyperframe==6.0.1
idna==3.7
importlib_metadata==8.4.0
Jinja2==3.1.4
loguru==0.7.2
lxml==5.3.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
msgpack==1.1.0
multidict==6.0.5
mutagen==1.47.0
nepattern==0.7.7
nonebot-adapter-onebot==2.4.4
nonebot-plugin-alconna==0.54.0
nonebot-plugin-apscheduler==0.5.0
nonebot-plugin-daily-oil-price==0.1.3
nonebot-plugin-localstore==0.7.0
nonebot-plugin-resolver==1.1.0
nonebot-plugin-waiter==0.8.0
nonebot2==2.4.0
orjson==3.10.5
PicImageSearch==3.11.2
pillow==11.0.0
pycryptodomex==3.20.0
pydantic==2.8.0
pydantic_core==2.20.0
PyExecJS==1.5.1
Pygments==2.18.0
pygtrie==2.5.0
pyquery==2.0.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
rfc3986==1.5.0
rich==13.7.1
shellingham==1.5.4
shelved-cache==0.3.1
six==1.16.0
sniffio==1.3.1
starlette==0.37.2
tarina==0.6.7
tenacity==9.0.0
tomli==2.0.1
typer==0.12.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
tzlocal==5.2
ujson==5.10.0
urllib3==2.2.2
uvicorn==0.30.1
uvloop==0.19.0
watchfiles==0.22.0
websockets==12.0
yarl==1.9.4
YetAnotherPicSearch==2.0.3
yt-dlp==2024.5.27
zipp==3.20.1

### 如何复现

安装后开始运行

### 实际行为

启动出现报错
11-28 10:42:44 [ERROR] nonebot | Failed to import "registry"
Traceback (most recent call last):
  File "/root/nonebot/bot.py", line 16, in <module>
    nonebot.load_plugins("YetAnotherPicSearch/YetAnotherPicSearch")  # 本地插件
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 53, in load_plugins
    return manager.load_all_plugins()
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 205, in load_all_plugins
    return set(
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 171, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__init__.py", line 8, in <module>
    from . import __main__ as __main__
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__main__.py", line 54, in <module>
    async def extract_images(msg: UniMsg[Segment]) -> list[Image]:
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1058, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/root/nonebot/.venv/lib/python3.10/site-packages/typing_extensions.py", line 2878, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class
11-28 10:42:44 [ERROR] nonebot | Failed to import "cache"
Traceback (most recent call last):
  File "/root/nonebot/bot.py", line 16, in <module>
    nonebot.load_plugins("YetAnotherPicSearch/YetAnotherPicSearch")  # 本地插件
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 53, in load_plugins
    return manager.load_all_plugins()
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 205, in load_all_plugins
    return set(
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 171, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__init__.py", line 8, in <module>
    from . import __main__ as __main__
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__main__.py", line 54, in <module>
    async def extract_images(msg: UniMsg[Segment]) -> list[Image]:
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1058, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/root/nonebot/.venv/lib/python3.10/site-packages/typing_extensions.py", line 2878, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class
11-28 10:42:44 [ERROR] nonebot | Failed to import "config"
Traceback (most recent call last):
  File "/root/nonebot/bot.py", line 16, in <module>
    nonebot.load_plugins("YetAnotherPicSearch/YetAnotherPicSearch")  # 本地插件
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 53, in load_plugins
    return manager.load_all_plugins()
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 205, in load_all_plugins
    return set(
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 171, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__init__.py", line 8, in <module>
    from . import __main__ as __main__
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__main__.py", line 54, in <module>
    async def extract_images(msg: UniMsg[Segment]) -> list[Image]:
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1058, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/root/nonebot/.venv/lib/python3.10/site-packages/typing_extensions.py", line 2878, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class
11-28 10:42:44 [ERROR] nonebot | Failed to import "nhentai_model"
Traceback (most recent call last):
  File "/root/nonebot/bot.py", line 16, in <module>
    nonebot.load_plugins("YetAnotherPicSearch/YetAnotherPicSearch")  # 本地插件
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 53, in load_plugins
    return manager.load_all_plugins()
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 205, in load_all_plugins
    return set(
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 171, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__init__.py", line 8, in <module>
    from . import __main__ as __main__
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__main__.py", line 54, in <module>
    async def extract_images(msg: UniMsg[Segment]) -> list[Image]:
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1058, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/root/nonebot/.venv/lib/python3.10/site-packages/typing_extensions.py", line 2878, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class
11-28 10:42:44 [ERROR] nonebot | Failed to import "utils"
Traceback (most recent call last):
  File "/root/nonebot/bot.py", line 16, in <module>
    nonebot.load_plugins("YetAnotherPicSearch/YetAnotherPicSearch")  # 本地插件
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 53, in load_plugins
    return manager.load_all_plugins()
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 205, in load_all_plugins
    return set(
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 171, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__init__.py", line 8, in <module>
    from . import __main__ as __main__
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__main__.py", line 54, in <module>
    async def extract_images(msg: UniMsg[Segment]) -> list[Image]:
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1058, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/root/nonebot/.venv/lib/python3.10/site-packages/typing_extensions.py", line 2878, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class
11-28 10:42:44 [ERROR] nonebot | Failed to import "data_source"
Traceback (most recent call last):
  File "/root/nonebot/bot.py", line 16, in <module>
    nonebot.load_plugins("YetAnotherPicSearch/YetAnotherPicSearch")  # 本地插件
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 53, in load_plugins
    return manager.load_all_plugins()
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 205, in load_all_plugins
    return set(
  File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 171, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__init__.py", line 8, in <module>
    from . import __main__ as __main__
  File "/root/nonebot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__main__.py", line 54, in <module>
    async def extract_images(msg: UniMsg[Segment]) -> list[Image]:
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1058, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/root/nonebot/.venv/lib/python3.10/site-packages/typing_extensions.py", line 2878, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: typing.Annotated[nonebot_plugin_alconna.uniseg.message.UniMessage, DependsInner(_uni_msg)] is not a generic class

**Comment by NekoAria** [comment]
试试 `v2.0.3.post1`

**Comment by lgc2333** [comment]
https://registry.nonebot.dev/plugin/YetAnotherPicSearch:YetAnotherPicSearch

**Comment by lgc2333** [comment]
> 试试 `v2.0.3.post1`

不可以这样，UniMsg是依赖注入

**Comment by NekoAria** [comment]
> > 试试 `v2.0.3.post1`
> 
> 不可以这样，UniMsg是依赖注入，UniMessage可以下标

你来改吧。nonebot 相关的东西我都没碰过了。

**Comment by lgc2333** [comment]
我目前是使用 ruff 进行 sort import、format 与 lint、以及 basedpyright 进行 type check，相关配置可以参见我的 workspace：https://github.com/lgc-NB2Dev/workspace/blob/main/pyproject.toml

**Comment by lgc2333** [comment]
做法是恢复原来的类型标注 `UniMsg`，不要加下标，这是一个 Annotated 类型的 TypeAlias，用于实现依赖注入

**Comment by NekoAria** [comment]
> [registry.nonebot.dev/plugin/YetAnotherPicSearch:YetAnotherPicSearch](https://registry.nonebot.dev/plugin/YetAnotherPicSearch:YetAnotherPicSearch)

严格说，这个测试结果也不准确。因为它用的版本还是 `2.0.3` ，就算之后发布 `2.0.3.post2` 还是一样。

**Comment by NekoAria** [comment]
已更新 `v2.0.3.post2`
