### ISSUE TITLE
[Bug?] TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by Todysheep** [lgc-NB2Dev/YetAnotherPicSearch#146]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

```txt
YetAnotherPicSearch==2.0.4
PicImageSearch==3.11.2
nonebot2==2.4.0
Python为3.12.7
```

### 列出安装的 Python 包

```txt
aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aiosignal==1.3.2
annotated-types==0.7.0
anyio==4.7.0
arclet-alconna==1.8.35
arclet-alconna-tools==0.7.10
arrow==1.3.0
attrs==24.2.0
Brotli==1.1.0
certifi==2024.12.14
click==8.1.7
colorama==0.4.6
cookit==0.8.4
cssselect==1.2.0
exceptiongroup==1.2.2
fastapi==0.115.6
fleep==1.0.1
frozenlist==1.5.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.7
httptools==0.6.4
httpx==0.28.1
hyperframe==6.0.1
idna==3.10
importlib_metadata==8.5.0
loguru==0.7.3
lxml==5.3.0
msgpack==1.1.0
multidict==6.1.0
nepattern==0.7.7
nonebot-adapter-onebot==2.4.6
nonebot-plugin-alconna==0.54.1
nonebot-plugin-waiter==0.8.0
nonebot2==2.4.0
PicImageSearch==3.11.2
pillow==11.0.0
propcache==0.2.1
pydantic==2.10.3
pydantic_core==2.27.1
pygtrie==2.5.0
pyquery==2.0.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
PyYAML==6.0.2
six==1.17.0
sniffio==1.3.1
starlette==0.41.3
tarina==0.6.8
tenacity==9.0.0
types-python-dateutil==2.9.0.20241206
typing_extensions==4.12.2
uvicorn==0.34.0
watchfiles==1.0.3
websockets==14.1
win32_setctime==1.2.0
yarl==1.18.3
YetAnotherPicSearch==2.0.4
zipp==3.21.0
```

### 如何复现

发送/搜图 [图片]后出现

### 实际行为

```pytb
12-15 22:16:29 [SUCCESS] nonebot | OneBot V11 *** | [message.group.normal]: Message 529043931 from ***@[ 群:***] '/搜图 [image:summary=[动画表情],file=000001464e61704361744f6e65426f747c4d736746696c657c327c3334373036333...,sub_type=1,file_id=000001464e61704361744f6e65426f747c4d736746696c657c327c3334373036333...,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhSZZ-0O...,file_size=154920,file_unique=7f8a3fc1fce59c5567ae82e93fc41ff0]'
12-15 22:16:29 [INFO] nonebot | Event will be handled by Matcher(type='message', module=YetAnotherPicSearch.__main__, lineno=330)
12-15 22:16:29 [INFO] nonebot | Matcher(type='message', module=YetAnotherPicSearch.__main__, lineno=330) running complete
12-15 22:16:29 [ERROR] nonebot | Running Matcher(type='message', module=YetAnotherPicSearch.__main__, lineno=330) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\anaconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\anaconda3\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\YetAnotherPicSearch\__main__.py", line 310, in search_handler
    else Network(proxies=config.proxy)
  File "C:\Users\Administrator\Desktop\toby\toby3\.venv\Lib\site-packages\PicImageSearch\network.py", line 58, in __init__
    self.client: AsyncClient = AsyncClient(
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
```

**Comment by lgc2333** [comment]
上游库问题， @NekoAria ，
但是因为nb目前最新稳定版本的httpx驱动器暂未支持httpx 0.28，先建议你降级httpx版本

**Comment by NekoAria** [comment]
> 上游库问题， @NekoAria ， 但是因为 nb 目前最新稳定版本的 httpx 驱动器暂未支持 httpx 0.28，先建议你降级 httpx 版本

然而 PicImageSearch 最新发布的版本还没升级到 httpx 0.28；就算它升级了，也该是这个插件锁定依赖版本，而不是让上游降级。

**Comment by lgc2333** [comment]
不是，我的意思是让上游把deprecated的写法换掉啊，没让升依赖版本

**Comment by lgc2333** [comment]
这个proxy参数在0.27是存在的

**Comment by NekoAria** [comment]
> 不是，我的意思是让上游把 deprecated 的写法换掉啊，没让升依赖版本

你如果说的上游是 httpx 本身，那它不太可能再支持 proxies 这个写法吧。
可如果你说的是 PicImageSearch，最新发布的版本还没适配 httpx 0.28 啊。

**Comment by NekoAria** [comment]
要解决这个运行问题不就是同时降级 YetAnotherPicSearch 到 v2.0.3.post2，并且 httpx 降级到 0.27 吗？

**Comment by lgc2333** [comment]
yaps不用降

**Comment by lgc2333** [comment]
> > 不是，我的意思是让上游把 deprecated 的写法换掉啊，没让升依赖版本
> 
> 你如果说的上游是 httpx 本身，那它不太可能再支持 proxies 这个写法吧。 可如果你说的是 PicImageSearch，最新发布的版本还没适配 httpx 0.28 啊。

对啊picimagesearch不是你有在负责吗，所以@你了

**Comment by NekoAria** [comment]
> 对啊 picimagesearch 不是你有在负责吗，所以 @你了

可这个报错和 PicImageSearch 没关系啊。
再说就算 PicImageSearch 适配了 httpx 0.28，那也该是 yaps 锁定 PicImageSearch 的版本在没适配 httpx 0.28 之前的版本。

还有，你不是才适配了 httpx 0.28： 5946d9a 。yaps 不降一样报错。

**Comment by lgc2333** [comment]
你仔细看看报错堆栈是哪里的proxies问题

**Comment by NekoAria** [comment]
> 你仔细看看报错堆栈是哪里的 proxies 问题

是你没看清楚啊，AsyncClient 不就是 httpx 的。

**Comment by lgc2333** [comment]
不是picimagesearch往asyncclient里传的**`proxies`**吗

**Comment by lgc2333** [comment]
所以我说建议先降级httpx版本到0.27，然后上游要做兼容0.28的修改

**Comment by lgc2333** [comment]
因为我想通知上游做更改，所以才@你的

**Comment by lgc2333** [comment]
另外虽说我更新日志写的是适配0.28，但实际内容也只是替换掉了插件内直接调用httpx部分的deprecated代码，httpx降级到0.27也能正常使用的，所以不用降yetanotherpicsearch

**Comment by NekoAria** [comment]
PicImageSearch v3.11.3 已发布
